### ISSUE TITLE
API-k létrehozása

### ISSUE THREAD

**Issue by npapp-dev** [Omega68/-gyf-kapu#11]
A másik csapattal projektével való kommunikációhoz szükséges API-k létrehozása. Kliensoldali csapatként a következőkre van szükségünk:
- paraméterek
- visszatérési érték
- a szerződése

**Comment by nagyph** [comment]
API elérhetősége: http://ugyfelkapu.fejlesztesgyak2015.info/api.php?module=erp_api&function=getIgenyles

**Comment by nagyph** [comment]
Módosítás API-n keresztül:
id: igénylés ID-ja
statusz: Erre lesz módosítva.

http://ugyfelkapu.fejlesztesgyak2015.info/api.php?module=erp_api&function=setIgenyles&id=92560&statusz=Folyamatban lévő
http://ugyfelkapu.fejlesztesgyak2015.info/api.php?module=erp_api&function=setIgenyles&id=92560&statusz=Passzív
http://ugyfelkapu.fejlesztesgyak2015.info/api.php?module=erp_api&function=setIgenyles&id=92560&statusz=Aktív
