### ISSUE TITLE
Felületkomponensek bekonfigurálása és létrehozása, a navigációval

### ISSUE THREAD

**Issue by npapp-dev** [Omega68/-gyf-kapu#12]
Felület komponensek: 
A komponenseket a /router/sites könyvtár alatt abba a fájlba kell bekonfigurálni, amelyik "site"-ra el akarod helyezni.

Ha ez megvan, akkor annak megfelelően ahogy be lett konfigurálnva a komponens, lehet mindig látható, vagy az url-ben lehet a komponensre hivatkozni, a nevével. 
Ez a komponens ?page=teszt url-re jön be, de alapértelmezetten is ez jelenik meg.

**Comment by npapp-dev** [comment]
@kruppakinga Ne haragudj, de nem lenne kedved ezt megcsinálni?

**Comment by kruppakinga** [comment]
Holnapra biztos nem tudom, de a jövő hétre meg tudom nézni.

**Comment by npapp-dev** [comment]
Bekonfigurálom őket. Majd a template-ben valahogy meg kéne változtatnia a menüstruktúrát, mivel nekünk nincsenek ajánlatok, és termékek, stb.

**Comment by npapp-dev** [comment]
Arra gondoltam, hogy az igényléseken belül kéne valahogy elérni  egy adott igényléshez tartozó kitöltött mezőket. Ha esetleg másfajta megközelítés is van, akkor írjátok ide.
