### ISSUE TITLE
A github pages részen a google doksi verziókezelésének megoldása

### ISSUE THREAD

**Issue by npapp-dev** [Omega68/-gyf-kapu#15]
@kruppakinga Tudod beszéltük, hogy meg kéne csinálni, hogy a github pages nevű branch-en verzió kezelve legyen az alkalmazásunk leírását tartalmazó doksi. Jó lenne ezt május 4-ig megcsinálni, ha nem gond? :)

**Comment by kruppakinga** [comment]
szerintem ezt nem szükséges május 4-ig megcsinálni. nyilván tök jó lenne, meg menő, de Elek szemszögéből ez semmit se jelent. mivel a feladatokkal kicsit lemaradásban vagyunk, én nem gondolom, hogy ezt a prioritásban előre kellene tenni. ha keddre meglesz minden, ami kell, akkor lehetne megcsinálni, mit gondolsz?

**Comment by npapp-dev** [comment]
Igen, teljesen egyetértek. Ha viszont tudod, hogy kell akkor én szívesen megcsinálom.

**Comment by kruppakinga** [comment]
helyette Wiki: https://github.com/Omega68/-gyf-kapu/wiki
