### ISSUE TITLE
Üzleti logika megvalósítása

### ISSUE THREAD

**Issue by npapp-dev** [Omega68/-gyf-kapu#16]
Sablonból kérvény létrehozása. Mezőkből kitöltött mező létrehozása. Sablon és mező kapcsolatának leprogramozása, stb. Vagyis ide jöhetne minden commit, ami az üzleti logikával kapcsolatos.

**Comment by kruppakinga** [comment]
elvállalom először azt, hogy az Admin be tudjon regisztrálni egy Ügyfelet

**Comment by kruppakinga** [comment]
itt még szerintem nagyon sok hiányzik, ezt helyre kéne tenni!

**Comment by kruppakinga** [comment]
akár több issue nyitása, hogy melyik modullal kapcsolatos logika
