### ISSUE TITLE
Módosítások validálása

### ISSUE THREAD

**Issue by npapp-dev** [Omega68/-gyf-kapu#17]
A módosítások megcsinálása, hogy hibakódokkal térjenek vissza, nem pedig szöveggel, és annak ellenőrzése, hogy az adott elem megfelelő tartalmú-e(Nem csak szóköz, stb.)

**Comment by npapp-dev** [comment]
Ez még nincs kész, pl. a mező esetén még nincsen meg ez.
@kruppakinga a mezők esetén a módosításokat is validálni kell, meg azt, hogy az adott mező lekérdezhető-e.

**Comment by kruppakinga** [comment]
a láthatóság bonyolultabb, meg az alap működéshez képest extra funkció. egyelőre e nélkül lesz.
