### ISSUE TITLE
Login felület, és bejelentkezés

### ISSUE THREAD

**Issue by npapp-dev** [Omega68/-gyf-kapu#18]
Bejelentkezés űrlap / kijelentkezés doboz. Lényegében az admin felület lenne.

**Comment by npapp-dev** [comment]
Még megpróbálom, az authentikáció modul-t is megszerkeszteni, és ha tudom, akkor a megfelelő komponenseket is legyártom.

**Comment by kruppakinga** [comment]
Betettem egy Profilt is, mert amúgy ugye elvárás lesz, hogy pl az Ügyfél jelszót változtasson, meg így szerintem egy profil kezdőlap jó lesz belépés után.

**Comment by kruppakinga** [comment]
A belépés, kijeletnkezés kész, az admin és ügyfél szét van választva. Az alapfeladat kész, az issue-t lezárom.
