### ISSUE TITLE
getObject bug: adatbázisból kiolvasott objektum adattagjai nem állítódnak be

### ISSUE THREAD

**Issue by kruppakinga** [Omega68/-gyf-kapu#19]
A perzisztencia manager-ben a getObject hibás (volt), illetve amúgy több metódusa is hibás, mert nem tér vissza a megfelelő osztályú objektummal.

Azt kijavítottam, hogy most már létrejön az adott példány, megkapja az ID-tészlegesen már működik. Viszont a többi adattag, amit megadtunk, az nem állítódik be. Magyarul nem tudok lekérdezni egy meglévő objektumot se az adatbázisból.

**Comment by npapp-dev** [comment]
A getObject() tényleg hibás, de a többi metódusa nem. Legalábbis a getObjectsByField és a másik biztos jó. Vagy mikor legutoljára néztem, akkor az volt. Másrészt az authentikacio is az egyiket használja az adatbázisba való belépés jogosultságának ellenőrzésére.
Másrészt mintha Elek azt mondta volna, hogy az adattagok akkor kérdeződnek le, mikor szükség van rá.

**Comment by kruppakinga** [comment]
a getfields is rossz igazából, mert az ügyfelek listázásánál csomó NULL-t dob vissza. most arra gondoltam, hogy nem lehet hogy neked a lokális adatbázisod nem úgy néz ki, mint amit valójában kell használnunk? mert a táblák ott nekünk pl ugyfel, nem Ugyfel... emiatt kell a lowercase. ezt nézd már meg magadnál légyszi.

**Comment by kruppakinga** [comment]
Másrészt mintha Elek azt mondta volna, hogy az adattagok akkor kérdeződnek le, mikor szükség van rá.
-> ezt nem tudtam, legalábbis nem emlékszem. akkor lezárom.
