### ISSUE TITLE
Delete methods

### ISSUE THREAD

**Issue by npapp-dev** [Omega68/-gyf-kapu#2]
A perzisztencia rétegnek kell tartalmaznia az SQL-eket az objektum(ok) törléséhez, de minden objektumnak magának kell rendelkeznie a törlése felől.

**Comment by kruppakinga** [comment]
ez kész van, ugye? a Persistent-ben van most a delete. vagy másra gondolt Elek? (nem emlékszem)

**Comment by npapp-dev** [comment]
Ahogy nèztem a kòdot, lehet, hogy kèsz van. Itt a lènyeg az lenne, hogy az ősosztàlyokbòl is töröljön. Szerintem ezt le lehet zàrni.
