### ISSUE TITLE
A megfelelő indexek felvétele az adatbázishoz

### ISSUE THREAD

**Issue by npapp-dev** [Omega68/-gyf-kapu#21]
Az órán beszélt indexeket szerintem célszerű lenne felvenni az adatbázisban.

**Comment by kruppakinga** [comment]
ügyfél, felhasználók: azon oszlop
igénylések: azon és a dátumok oszlopra
A kereséstől függ, hogy még milyen kell rá. Ha aktuális lesz, nyissuk újra, egyelőre kész a task.
