### ISSUE TITLE
Találatok száma, lapozás nem működik

### ISSUE THREAD

**Issue by kruppakinga** [Omega68/-gyf-kapu#24]
Nem 50-et jelenít meg pl., illetve a többi funkció sem jó még.

**Comment by npapp-dev** [comment]
Úgy gondoltam a process() metódusba lehetne írni, hogy nézze meg, hogy mire kattintott lent az user, és ott kéne a metódusban ezt módosítani. Mondjuk egy feltételes utasításban, megnézné, hogy pontosan, hogy legyen. Valahogy így if(!empty($_POST['selected'])). Vagy ti mit gondoltok?

**Comment by kruppakinga** [comment]
igen, a logoutosban ahogy csináltad, meg amit most kommitoltam (az ügyfél törlése a felületről) abban így van, megnézhetnéd ott. van kedved ezzel foglalkozni?

**Comment by kruppakinga** [comment]
több lépésben a lapozás nem működik.
esetleg feladatként hogy az utolsó lapon nem jelenik meg a következő gomb, de ez lehet inkább extra

**Comment by Omega68** [comment]
Itt szerintem elakadtam, nagyon valószínű, hogy a fő gond az, hogy a php osztály példánya egy kérés kielégítésének idejéig létezik.

**Comment by npapp-dev** [comment]
Itt még van egy hiba, de nem tudom committolni, mert nem írja ki, hogy eltérés lenne a git repo és a sajátom között. Pedig egyáltalán nem egyezik.

**Comment by npapp-dev** [comment]
Ez a sok commit nem tudom, hogy történt. :(
