### ISSUE TITLE
Az ügyfélhez tartozó igénylések kilistázásához szükséges aloldal létrehozása

### ISSUE THREAD

**Issue by npapp-dev** [Omega68/-gyf-kapu#25]
Lényegében, egy a táblában szereplő igénylések gomb lenyomásával jönne fel egy lista, ami az adott user-hez tartozó kitöltött igényléseket mutatja meg. Ebben valahogy azt is meg kéne oldani, hogy az adott igényléshez tartozó kitöltött mezők is megjelenhessenek.
A facebook-on van egy ötlet ennek megvalósítására.

**Comment by kruppakinga** [comment]
aloldal kész, a többi feladat átvezetve külön issue-ba
