### ISSUE TITLE
Felhasználó törlésekor nem törlődik a hozzátartozó Ügyfél

### ISSUE THREAD

**Issue by kruppakinga** [Omega68/-gyf-kapu#30]

**Comment by npapp-dev** [comment]
Hát igen, ez a delete methods nevezetű issue lett volna: #2

**Comment by nagyph** [comment]
Az ügyfél az egy Ügyfél objektum (ami a felhasználóból van örököltetve), tehát csak egy objektum létezik ami az Ügyfél osztályból van példányosítva. Tehát Felhasználó objektum nem létezik, vagyis azt nem is lehet törölni.

**Comment by npapp-dev** [comment]
De az adatbàzisban redundànsan vannak az adatok, nemde? Vagyis ha az ugyfel torlodik, akkor a felhasznalo is. Legalabbis szerintem. Olyan nincs,  hogy valaki felhasznalokent jelen van, de ugyfelkent vagy adminkent nem. Bar ez lehetne kulon issue is.

**Comment by kruppakinga** [comment]
működik
