### ISSUE TITLE
Keretrendszer használata: felület komponensek, modulok létrehozása

### ISSUE THREAD

**Issue by kruppakinga** [Omega68/-gyf-kapu#8]

**Comment by npapp-dev** [comment]
Rákérdeztünk a másik csapatnál, és nekik egy osztály = modul lett végül.

**Comment by npapp-dev** [comment]
Magamra veszem, és valószínűleg a 04.25.-re délutánjára meglesz. Nem tűnik nagy dolognak a példa alapján. Kár, hogy deadline-okat nem lehet beállítani a github-on.

**Comment by npapp-dev** [comment]
Fixed with 3bc8c3761827aa8fe7745d1edf64e414e0a9be4b

Bocsi, elfejtettem az issue id-ját belerakni a commit kommentjébe. :(

**Comment by npapp-dev** [comment]
@kruppakinga a felület komponenseket egy külön issue-ba vettem, ha nem gond?
Még amúgy a perzisztencia modulon gondolkodok, mivel a másik csapat elég furán csinálta meg, és még nem értem, hogy ennek mi az oka.
